### ISSUE TITLE
Install d3 in ES6 modules environment

### ISSUE THREAD

**Issue by EMHmark7** [jaredreich/vue-d3#1]
See next comment

**Comment by MarcTe** [comment]
Full question at http://forum.vuejs.org/topic/4972/install-d3-in-es6-modules-environment

**Comment by MarcTe** [comment]
Basically, the problem is how we can declare it in a modularized app environment. At least within a specific module (importing).

**Comment by EMHmark7** [comment]
It says: Cannot read property 'select' of undefined:
 <div id="brd-area" class = "board-area"></div> 

<script>var svg = this.$d3.select("#brd-area").append("svg") </script>

**Comment by MarcTe** [comment]
It says: Cannot read property 'select' of undefined:
 <div id="brd-area" class = "board-area"></div> 

<script>var svg = this.$d3.select("#brd-area").append("svg") // used here</script>

**Comment by EMHmark7** [comment]
It says: Cannot read property 'select' of undefined:
 <div id="brd-area" class = "board-area"></div> 

<script>var svg = this.$d3.select("#brd-area").append("svg") </script>
