### ISSUE TITLE
Cannot read property 'select' of undefined:

### ISSUE THREAD

**Issue by EMHmark7** [jaredreich/vue-d3#2]
See next comment

**Comment by EMHmark7** [comment]
I am not able to post my issue, it hides almost everything. Please see [http://forum.vuejs.org/topic/4972/install-d3-in-es6-modules-environment](url)

**Comment by jaredreich** [comment]
link is broken

**Comment by EMHmark7** [comment]
Link is not broken, it is a bug from github. Just copy paste the URL. You can go to the last posts. My remaning problem is call the d3 code at object initialisation. Actually, I need to change a data in it, and change it back. Would be nice if you can evaluate my way to use d3 in vue. Thanks. Marc

**Comment by jaredreich** [comment]
This is just a D3 wrapper my friend, you're in the wrong place.
